name: Admin S3 Deploy

on:
  push:
    branches: [ feat/admin ]
  pull_request:
    branches: [ feat/admin ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: ${{secrets.SERVER_NODE_ENV}}
      PORT: ${{secrets.SERVER_PORT}}
      LOG_DIR: ${{secrets.SERVER_LOG_DIR}}
      # DB
      DB_HOST: ${{secrets.SERVER_DB_HOST}}
      DB_PORT: ${{secrets.SERVER_DB_PORT}}
      DB_NAME: ${{secrets.SERVER_DB_NAME}}
      DB_USER: ${{secrets.SERVER_DB_USER}}
      DB_USER_PWD: ${{secrets.SERVER_DB_USER_PWD}}
      # JWT
      JWT_SECRET: ${{secrets.SERVER_JWT_SECRET}}
      JWT_EXP: ${{secrets.SERVER_JWT_EXP}}
      # AWS
      AWS_ACCESS_KEY_ID: ${{secrets.SERVER_AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.SERVER_AWS_SECRET_ACCESS_KEY}}
      AWS_REGION: ${{secrets.SERVER_AWS_ASSETS_BUCKET_REGION}}
      AWS_ASSETS_BUCKET_REGION: ${{secrets.SERVER_AWS_ASSETS_BUCKET_REGION}}
      AWS_ASSETS_BUCKET: ${{secrets.SERVER_AWS_ASSETS_BUCKET}}
      AWS_ASSETS_DOMAIN: ${{secrets.SERVER_AWS_ASSETS_DOMAIN}}

    steps:
    - name: Check out repo master branch
      uses: actions/checkout@v2
      with:
          repository: mohanzeal/aibestapps
          ref: master
          token: ${{ secrets.ALL_AIBA_DEPLOY }}

    - name: Get yarn cache directory path
      id: yarn-cache-server-folder
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

    - name: Cache Yarn server node_modules
      uses: actions/cache@v2
      id: yarn-cache-server
      with:
          path: |
            **/node_modules
            ${{ steps.yarn-cache-server-folder.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
    - name: Install dependencies
      run: yarn install --immutable

    - name: build all dependant packages for admin
      run: yarn build:global-types

    - name: build all admin dependant packages
      run: yarn build:admin

    - name: Upload `spa` folder to S3 bucket
      run: aws s3 sync packages/admin/dist/spa s3://admin.aibestapps.com/