name: Node Server API CI

on:
  push:
    branches: [ deploy/server ]
  pull_request:
    branches: [ deploy/server ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: ${{secrets.SERVER_NODE_ENV}}
      PORT: ${{secrets.SERVER_PORT}}
      LOG_DIR: ${{secrets.SERVER_LOG_DIR}}
      # DB
      DB_HOST: ${{secrets.SERVER_DB_HOST}}
      DB_PORT: ${{secrets.SERVER_DB_PORT}}
      DB_NAME: ${{secrets.SERVER_DB_NAME}}
      DB_USER: ${{secrets.SERVER_DB_USER}}
      DB_USER_PWD: ${{secrets.SERVER_DB_USER_PWD}}
      # JWT
      JWT_SECRET: ${{secrets.SERVER_JWT_SECRET}}
      JWT_EXP: ${{secrets.SERVER_JWT_EXP}}
      # AWS
      AWS_ACCESS_KEY_ID: ${{secrets.SERVER_AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.SERVER_AWS_SECRET_ACCESS_KEY}}
      AWS_REGION: ${{secrets.SERVER_AWS_ASSETS_BUCKET_REGION}}
      AWS_ASSETS_BUCKET_REGION: ${{secrets.SERVER_AWS_ASSETS_BUCKET_REGION}}
      AWS_ASSETS_BUCKET: ${{secrets.SERVER_AWS_ASSETS_BUCKET}}
      AWS_ASSETS_DOMAIN: ${{secrets.SERVER_AWS_ASSETS_DOMAIN}}
      # APP
      VUE_API_DOMAIN: ${{secrets.APP_VUE_API_DOMAIN}}
      VUE_APP_PORT: ${{secrets.APP_VUE_APP_PORT}}
      VUE_DOMAIN_NAME: ${{secrets.APP_VUE_DOMAIN_NAME}}
      VUE_APP_DOMAIN: ${{secrets.APP_VUE_APP_DOMAIN}}
      VUE_ASSETS_DOMAIN: ${{secrets.APP_VUE_ASSETS_DOMAIN}}

    steps:
    - name: Check out repo master branch
      uses: actions/checkout@v2
      with:
          repository: mohanzeal/aibestapps
          ref: master
          token: ${{ secrets.ALL_AIBA_DEPLOY }}

    - name: Get yarn cache directory path
      id: yarn-cache-server-folder
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

    - name: Cache Yarn server node_modules
      uses: actions/cache@v2
      id: yarn-cache-server
      with:
          path: |
            **/node_modules
            ${{ steps.yarn-cache-server-folder.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn install --immutable

    - name: remove existing build_artifacts
      run: rm -rf build_artifacts.zip

    - name: build all global-types,server & app packages
      run: yarn build:all
    
    - name: zip build artifacts for global-types,server,app
      run: zip -r build_artifacts.zip packages/global-types/build packages/server/build packages/app/dist/ssr/

    - name: Upload server `build` folder to S3
      run: aws s3 cp build_artifacts.zip s3://aibestapps-backups/prod/